### ISSUE TITLE
Not an issue a request... Can you add a name_filter / keyword filter?

### ISSUE THREAD

**Issue by santiagodemierre** [jonwaldstein/blocks-for-eventbrite#2]
I wanted to do some microsurgery on your script and ended up breaking it with an axe lol

I'm new to programming and I have no idea how to make this work... you haven't made it easy with all the ninja trickery, stringconcatenation class css thingy

I'm trying to use your plugin, but I want to only show the events matching the content of the page. A keyword, name_filter filter would be awesome.

Please and thank you :-)

**Comment by santiagodemierre** [comment]
/v3/users/me/events/?name_filter=word1+word2&order_by=start_asc&status=live&time_filter=current_future&token=abcdedfg

works when I visit it but not if I change it on the 
blocks-for-eventbrite.php


or in 
blocks-for-eventbrite/src/components/EditBlock.js

<PanelRow>
						<TextControl
							label="Name Filter"
							help="What events do you want to show?."
							value={ name_filter }
							onChange={ ( name_filter ) =>
								setAttributes( {
									name_filter: name_filter,
								} )
							}
						/>
					</PanelRow>

**Comment by jonwaldstein** [comment]
Hey @santiagodemierre,

I would be happy to add this feature.  You're definitely on the right track with the name_filter! There's a few more steps & testing involved that i'll have to go through to add this so give me a couple days to get this working.

**Comment by jonwaldstein** [comment]
@santiagodemierre this feature has been pushed to the WordPress plugin: https://wordpress.org/plugins/blocks-for-eventbrite/
